config/routes.rb
Rails.application.routes.draw do
  # Deviseによるユーザー認証
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    passwords: 'devise/passwords',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admin', skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'dashboard#index'  # 管理者用のダッシュボードのルート
    resources :posts, only: [:index, :show, :edit, :update, :destroy]  # 投稿の一覧、詳細、削除
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'confirm_deactivation'
        patch 'deactivate'  # 退会処理をPATCHに変更
      end
    end
    resources :communities, only: [:index, :show, :edit, :update, :destroy]  # 管理者用コミュニティルート
    resources :comments, only: [:index, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :posts do
      resources :comments, only: [:destroy]
    end
  end

  resources :users, only: [:show] do
    member do
      get 'confirm_deactivation' # 退会確認ページ
      patch 'deactivate' # 退会処理
    end
  end

  # 投稿に関するルーティング
  resources :posts do
    collection do
      get 'my_posts'         # ログインユーザーの投稿一覧
      get 'commented_posts'  # ログインユーザーがコメントした投稿一覧
    end
    resources :comments, only: [:create, :destroy]  # コメントの作成・削除
  end

  # プロフィールページに関連するルーティング
  get 'profile', to: 'users#show', as: 'user_profile'
  post 'profile', to: 'users#create_post'

  # プロフィール編集
  resources :users, only: [:index, :show, :edit, :update]

  # コミュニティに関するルーティング
  resources :communities do
    resources :posts, controller: 'community_posts', only: [:new, :create]
    member do
      post 'join', to: 'communities#join'
      delete 'leave', to: 'communities#leave'
    end
    resources :posts, only: [:new, :create]
  end

  # 静的ページ
  get 'about', to: 'pages#about'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_of_service', to: 'pages#terms_of_service', as: 'terms_of_service'
  get 'contact', to: 'pages#contact', as: 'contact'

  # 作成したコミュニティ一覧
  get 'my_communities', to: 'users#my_communities', as: 'my_communities'

  # 参加中のコミュニティ一覧
  get 'joined_communities', to: 'users#joined_communities', as: 'joined_communities'

  # トップページ
  get 'top', to: 'users#top', as: 'top'

  # ゲストログイン専用ページ
  get 'guest_dashboard', to: 'users#guest_dashboard', as: 'guest_dashboard'

  # お問い合わせページ
  get  'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  # 感謝ページのルート
  get 'thank_you', to: 'pages#thank_you'

  # ログイン画面をrootに設定し、ログアウトルートも定義
  devise_scope :user do
    root to: 'devise/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    # 管理者用ダッシュボードの処理
  end
  
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<div class="page-background">
<div class="dashboard">
  <h1 class="dashboard-title">管理者トップ</h1>

    <div class="dashboard-link">
      <%= link_to '投稿管理', admin_posts_path, class: 'btn btn-primary' %>
    </div>
    <div class="dashboard-link">
      <%= link_to 'コメント管理', admin_comments_path, class: 'btn btn-primary' %>
    </div>
    <div class="dashboard-link">
      <%= link_to 'ユーザー管理', admin_users_path, class: 'btn btn-primary' %>
    </div>
    <div class="dashboard-link">
      <%= link_to 'コミュニティ管理', admin_communities_path, class: 'btn btn-primary' %>
    </div>
    <div class="dashboard-link">
      <%= link_to 'お問い合わせ内容確認', admin_inquiries_path, class: 'btn btn-primary' %>
    </div>

  <div class="admin-signout">
    <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, data: { confirm: "ログアウトしますか？", turbolinks: false }, class: 'btn btn-danger' %>
  </div>

</div>