config/routes.rb
Rails.application.routes.draw do
  # Deviseによるユーザー認証
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    passwords: 'devise/passwords',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admin', skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'dashboard#index'  # 管理者用のダッシュボードのルート
    resources :posts, only: [:index, :show, :edit, :update, :destroy]  # 投稿の一覧、詳細、削除
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'confirm_deactivation'
        patch 'deactivate'  # 退会処理をPATCHに変更
      end
    end
    resources :communities, only: [:index, :show, :edit, :update, :destroy]  # 管理者用コミュニティルート
    resources :comments, only: [:index, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :posts do
      resources :comments, only: [:destroy]
    end
  end

  resources :users, only: [:show] do
    member do
      get 'confirm_deactivation' # 退会確認ページ
      patch 'deactivate' # 退会処理
    end
  end

  # 投稿に関するルーティング
  resources :posts do
    collection do
      get 'my_posts'         # ログインユーザーの投稿一覧
      get 'commented_posts'  # ログインユーザーがコメントした投稿一覧
    end
    resources :comments, only: [:create, :destroy]  # コメントの作成・削除
  end

  # プロフィールページに関連するルーティング
  get 'profile', to: 'users#show', as: 'user_profile'
  post 'profile', to: 'users#create_post'

  # プロフィール編集
  resources :users, only: [:index, :show, :edit, :update]

  # コミュニティに関するルーティング
  resources :communities do
    resources :posts, controller: 'community_posts', only: [:new, :create]
    member do
      post 'join', to: 'communities#join'
      delete 'leave', to: 'communities#leave'
    end
    resources :posts, only: [:new, :create]
  end

  # 静的ページ
  get 'about', to: 'pages#about'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_of_service', to: 'pages#terms_of_service', as: 'terms_of_service'
  get 'contact', to: 'pages#contact', as: 'contact'

  # 作成したコミュニティ一覧
  get 'my_communities', to: 'users#my_communities', as: 'my_communities'

  # 参加中のコミュニティ一覧
  get 'joined_communities', to: 'users#joined_communities', as: 'joined_communities'

  # トップページ
  get 'top', to: 'users#top', as: 'top'

  # ゲストログイン専用ページ
  get 'guest_dashboard', to: 'users#guest_dashboard', as: 'guest_dashboard'

  # お問い合わせページ
  get  'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  # 感謝ページのルート
  get 'thank_you', to: 'pages#thank_you'

  # ログイン画面をrootに設定し、ログアウトルートも定義
  devise_scope :user do
    root to: 'devise/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  belongs_to :community, optional: true  # コミュニティがない投稿も可能にするため `optional: true`

  # バリデーション
  validates :title, presence: true, length: { maximum: 50 }, unless: :in_community?
  validates :description, presence: true, length: { maximum: 3000 }, unless: :in_community?
  validates :description, presence: true, length: { maximum: 1000 }, if: :in_community?

  # コミュニティ内かどうかを判定するメソッド
  def in_community?
    community.present?
  end

  # 画像表示メソッド
  def display_image(size = [500, 500])
    image.variant(resize_to_limit: size).processed
  end

  # 仮想属性として remove_image を定義
  attr_accessor :remove_image

  # remove_image が '1' の場合、画像を削除する
  before_save :purge_image, if: -> { remove_image == '1' }

  private

  # 画像削除の処理
  def purge_image
    image.purge if image.attached?
  end

end

app/controllers/admin/posts_controller.rb
# app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!  # 管理者認証
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present?
      @posts = Post.where(community_id: nil) # コミュニティに属さない投稿のみ
                   .where("title LIKE ?", "%#{params[:search]}%")
                   .or(Post.where("description LIKE ?", "%#{params[:search]}%").where(community_id: nil))
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(20)
    else
      @posts = Post.where(community_id: nil) # コミュニティに属さない投稿のみ
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(20)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :asc) # ここでコメントを取得
    @comments_count = @comments.size
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.community_id.present?
      # コミュニティに関連する投稿の場合はコミュニティ詳細ページにリダイレクト
      community = @post.community
      @post.destroy
      redirect_to admin_community_path(community)
    else
      # コミュニティに関連しない投稿の場合はマイ投稿一覧にリダイレクト
      @post.destroy
      redirect_to admin_posts_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image, :user_id, :remove_image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :restrict_guest_user, only: [:new, :create, :edit, :update, :destroy, :my_posts, :commented_posts]

  def index
    if params[:search].present?
      @posts = Post.where(community_id: nil) # コミュニティに属さない投稿のみ
                   .where("title LIKE ?", "%#{params[:search]}%")
                   .or(Post.where("description LIKE ?", "%#{params[:search]}%").where(community_id: nil))
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(20)
    else
      @posts = Post.where(community_id: nil) # コミュニティに属さない投稿のみ
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(20)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :asc) # ここでコメントを取得
    @comments_count = @comments.size
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.community_id.present?
      # コミュニティに関連する投稿の場合はコミュニティ詳細ページにリダイレクト
      community = @post.community
      @post.destroy
      redirect_to community_path(community)
    else
      # コミュニティに関連しない投稿の場合はマイ投稿一覧にリダイレクト
      @post.destroy
      redirect_to my_posts_posts_path
    end
  end

  # 自分の投稿一覧
  def my_posts
    if params[:search].present?
      @posts = current_user.posts.where(community_id: nil) # コミュニティに属さない投稿のみ
                                 .where("title LIKE ?", "%#{params[:search]}%")
                                 .or(Post.where("description LIKE ?", "%#{params[:search]}%").where(community_id: nil))
                                 .order(created_at: :desc)
                                 .page(params[:page])
                                 .per(20)
    else
      @posts = current_user.posts.where(community_id: nil) # コミュニティに属さない投稿のみ
                                 .order(created_at: :desc)
                                 .page(params[:page])
                                 .per(20)
    end
  end

  # コメントした投稿一覧を表示するアクション
  def commented_posts
    if params[:search].present?
      @posts = Post.joins(:comments)
                   .where(comments: { user_id: current_user.id }, community_id: nil)
                   .where("posts.title LIKE ?", "%#{params[:search]}%")
                   .or(Post.joins(:comments).where("posts.description LIKE ?", "%#{params[:search]}%").where(comments: { user_id: current_user.id }, community_id: nil))
                   .order('posts.created_at DESC')
                   .distinct
                   .page(params[:page])
                   .per(20)
    else
      @posts = Post.joins(:comments)
                   .where(comments: { user_id: current_user.id }, community_id: nil)
                   .order('posts.created_at DESC')
                   .distinct
                   .page(params[:page])
                   .per(20)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user!
    redirect_to post_path unless @post.user == current_user
  end

  def post_params
    params.require(:post).permit(:title, :description, :image, :user_id, :remove_image)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/commented_posts.html.erb
<div class="page-background">
  <div class="posts-page">
    <h1 class="posts-title">コメントした投稿一覧</h1>

    <%= render 'shared/search_form', search_path: commented_posts_posts_path %>

    <div class="communities-actions">
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-primary' %>
    </div>

    <div class="posts-grid">
      <% if @posts.any? %>
        <% @posts.each do |post| %>
          <%= render 'shared/post_item', post: post %>
        <% end %>
      <% else %>
        <div class="no-comment">
          <p class="no-posts">コメントした投稿がありません。</p>
        </div>
      <% end %>
    </div>

    <%= render 'shared/pagination', items: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="page-background">
  <div class="edit-post-page">
    <h1 class="edit-post-page-title">投稿を編集する</h1>

    <%= render 'shared/error_messages', resource: @post %>

    <%= form_with(model: @post, local: true) do |form| %>

      <div class="edit-post-title">
        <%= form.label :title, 'タイトル', class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="edit-post-description">
        <%= form.label :description, '説明文', class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control edit-post-textarea' %>
      </div>

      <div class="edit-post-image">
        <%= form.label :image, '画像', class: 'form-label' %>
        <%= form.file_field :image, class: 'form-control-file' %>
        <% if @post.image.attached? %>
          <div class="current-image">
            <%= image_tag @post.display_image, alt: "現在の画像", class: "img-fluid current-post-image" %>
          </div>
          <div class="remove-image-option">
            <%= form.check_box :remove_image, {}, '1', '0' %> 画像を削除する
          </div>
        <% end %>
      </div>

      <div class="edit-post-actions">
        <%= form.submit '更新する', class: 'btn btn-primary', data: { confirm: '本当に更新しますか？' } %>
        <%= link_to 'キャンセル', post_path(@post), class: 'btn btn-secondary cancel-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="page-background">
  <div class="posts-page">
    <h1 class="posts-title">投稿一覧</h1>

    <%= render 'shared/search_form', search_path: posts_path %>

    <div class="new-post-link">
      <%= link_to '新規投稿', new_post_path, class: 'btn btn-primary' %>
    </div>

    <div class="posts-grid">
      <% if @posts.any? %>
        <% @posts.each do |post| %>
          <%= render 'shared/post_item', post: post %>
        <% end %>
      <% else %>
        <div class="no-comment">
          <p class="no-posts">投稿がありません。</p>
        </div>
      <% end %>
    </div>

    <%= render 'shared/pagination', items: @posts %>
  </div>
</div>

app/views/posts/my_posts.html.erb
<div class="page-background">
  <div class="posts-page">
    <h1 class="posts-title">あなたの投稿一覧</h1>

    <%= render 'shared/search_form', search_path: my_posts_posts_path %>

    <div class="communities-actions">
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-primary' %>
    </div>

    <div class="new-post-link">
      <%= link_to '新規投稿', new_post_path, class: 'btn btn-primary' %>
    </div>

    <div class="posts-grid">
      <% if @posts.any? %>
        <% @posts.each do |post| %>
          <%= render 'shared/post_item', post: post %>
        <% end %>
      <% else %>
        <div class="no-comment">
          <p class="no-posts">まだ投稿がありません。</p>
        </div>
      <% end %>
    </div>

    <%= render 'shared/pagination', items: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="page-background">
  <div class="new-post-page">
    
    <%= form_with(model: @post, local: true) do |form| %>
      <h1 class="new-post-title">新規投稿</h1>
      <%= render 'shared/error_messages', resource: @post %> <!-- エラーメッセージの部分 -->

      <div class="field title-field">
        <strong><%= form.label :title, 'タイトル', class: 'form-label' %></strong>
        <%= form.text_field :title, class: 'form-control title-textfield', placeholder: '50文字以内', maxlength: 50 %>
      </div>

      <div class="field title-description">
        <strong><%= form.label :description, '説明文', class: 'form-label' %></strong>
        <%= form.text_area :description, class: 'form-control description-textarea', placeholder: '3000文字以内', maxlength: 3000 %>
      </div>

      <div class="field title-image">
        <strong><%= form.label :image, '画像', class: 'form-label' %></strong>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="mt-3">
        <%= form.submit '投稿', class: 'btn btn-primary', data: { confirm: '本当に投稿しますか？' } %>
      </div>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="page-background">
  <div class="post-detail">

    <div class="post-detail-header">
    <!-- ユーザー情報の表示部分 -->
      <div class="left-section">
        <% if @post.user.profile_image.attached? %>
          <%= link_to user_path(@post.user.id) do %>
            <%= image_tag @post.user.profile_image.variant(resize_to_fill: [40, 40]), class: "post-user-icon" %>
          <% end %>
        <% else %>
          <%= link_to user_path(@post.user.id) do %>
            <%= image_tag asset_path('no_image_photo.jpg'), size: "40x40", class: "post-user-icon" %>
          <% end %>
        <% end %>
        <%= link_to @post.user.display_name, user_path(@post.user.id), class: 'post-detail-username' %>
      </div>

      <!-- 3点リーダー -->
      <div class="dropdown right-section">
        <div class="dropdown-toggle" data-comment-id="<%= @post.id %>"><i class="fa-solid fa-ellipsis"></i></div>
        <div class="dropdown-menu" id="dropdown-menu-<%= @post.id %>">
          <% if @post.user == current_user %>
            <%= link_to '投稿を編集する', edit_post_path(@post), class: 'dropdown-item edit-post-btn' %>
            <%= link_to '投稿を削除する', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'dropdown-item delete-post-btn' %>
          <% else %>
            <p class="dropdown-item no-actions">可能な操作はありません</p>
          <% end %>
        </div>
      </div>

    </div>

    <h1 class="post-detail-title"><%= @post.title %></h1>
    <p class="post-detail-description"><%= @post.description %></p>

    <% if @post.image.attached? %>
      <p class="post-image"><%= image_tag @post.display_image([500, 500]), loading: 'lazy', class: "img-fluid" %></p>
    <% end %>

    <p class="post-detail-date"><%= @post.created_at.in_time_zone('Asia/Tokyo').strftime("%Y/%m/%d %H:%M") %></p>

    <div class="comments-section">
      <h2>コメント一覧(<%= @comments_count %>)</h2>
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
          <div class="comment-container">
            <div class="comment-header">
              <div class="left-section">
                <% if comment.user.profile_image.attached? %>
                  <%= link_to user_path(comment.user) do %>
                    <%= image_tag comment.user.profile_image.variant(resize_to_fill: [30, 30]), class: "comment-user-icon" %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(comment.user) do %>
                    <%= image_tag asset_path('no_image_photo.jpg'), size: "30x30", class: "comment-user-icon" %>
                  <% end %>
                <% end %>
                <%= link_to comment.user.display_name, user_path(comment.user), class: 'comment-username' %>
              </div>

              <div class="right-section">
                <div class="dropdown">
                  <div class="dropdown-toggle" data-comment-id="<%= comment.id %>"><i class="fa-solid fa-ellipsis"></i></div>
                  <div class="dropdown-menu" id="dropdown-menu-<%= comment.id %>">
                    <% if comment.id.present? && comment.user == current_user %>
                      <%= link_to 'コメントを削除する', post_comment_path(comment.post, comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'dropdown-item delete-comment-btn' %>
                    <% else %>
                      <p class="dropdown-item no-actions">可能な操作はありません</p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="comment-content">
              <p><%= comment.content %></p>
                <p class="comment-date"><%= comment.created_at.in_time_zone('Asia/Tokyo').strftime("%Y/%m/%d %H:%M") %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="no-posts">コメントはまだありません。</p>
      <% end %>
    </div>

    <!-- エラーメッセージの表示 -->
    <%= render 'shared/error_messages', resource: @comment %>

    <div class="comment-form-container">
      <div class="user-icon-wrapper">
        <% if current_user.profile_image.attached? %>
          <%= image_tag current_user.profile_image.variant(resize_to_fill: [30, 30]), class: "user-icon" %>
        <% else %>
          <%= image_tag asset_path('no_image_photo.jpg'), size: "30x30", class: "user-icon" %>
        <% end %>
      </div>

      <div class="comment-form-wrapper">
        <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
        <div class="comment-form">
          <%= form.text_area :content, class: "form-control comment-input", placeholder: "1000文字以内" %>
          <%= form.submit 'コメントする', class: 'btn btn-primary comment-submit-btn', data: { confirm: '本当にコメントしますか？' } %>
        </div>
      <% end %>
    </div>

  </div>

</div>